import { Poppins, DM_Sans } from "next/font/google";
import "./globals.css";
import ReduxProvider from "../components/redux-provider";
import { ThemeProvider } from "../components/theme-provider";
import ThemeSync from "../components/theme-sync";
import ClientLayout from "./(app)/components/ClientLayout";
import QueryProvider from "@/components/providers/QueryProvider";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
  display: "swap",
});

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-dm-sans",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fontClasses = `${poppins.variable} ${dmSans.variable} antialiased`;

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={fontClasses}>
        <ReduxProvider>
          <QueryProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="light"
              enableSystem={false}
            >
              <ThemeSync />
              <div className="flex min-h-screen flex-col">
                <ClientLayout>
                  <main className="flex-1 bg-background">
                    {children}
                  </main>
                </ClientLayout>
              </div>
            </ThemeProvider>
          </QueryProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
