import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReduxProvider from "../components/redux-provider";
import { ThemeProvider } from "../components/theme-provider";
import ThemeSync from "../components/theme-sync";

/**
 * Global font configuration
 * Loaded once at the root to avoid duplication and reflows
 */
const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
});

/**
 * App-wide metadata
 * Keep this minimal here; move to route-level when needed
 */
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fontClasses = `${geistSans.variable} ${geistMono.variable} antialiased`;

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={fontClasses}>
        <ReduxProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <ThemeSync />
            {children}
          </ThemeProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
