import { Poppins } from "next/font/google";
import "./globals.css";
import ReduxProvider from "../components/redux-provider";
import { ThemeProvider } from "../components/theme-provider";
import ThemeSync from "../components/theme-sync";
import ClientLayout from "./(app)/components/ClientLayout";

/**
 * Global font configuration
 * Poppins is used as per Figma design
 */
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});

/**
 * App-wide metadata
 * Keep this minimal here; move to route-level when needed
 */
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fontClasses = `${poppins.variable} antialiased`;

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={fontClasses}>
        <ReduxProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem={false}
          >
            <ThemeSync />
            <div className="flex min-h-screen flex-col">
              <ClientLayout>
                <main className="flex-1 bg-background">
                  {children}
                </main>
              </ClientLayout>
            </div>
          </ThemeProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
