name: hstp_ui DEV Deployment

on:
    push:
        branches:
            - dev

jobs:
    deploy:
        runs-on: ubuntu-latest

        env:
            DEPLOYMENT_DIRECTORY: "/var/www/sites/dev-hstp.hammerbyte.co.in/"
            REPO: "hstp_ui"
            BRANCH: ${{ github.ref_name }}
            PORT: 12000

        steps:
            - name: Preparing SSH
              run: sudo apt-get install -y sshpass

            - name: SSH Deployment
              run: |
                  sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no "${{ secrets.SSH_USERNAME }}@${{ secrets.HOSTING_SERVER }}" << 'EOF'
                    set -e
                    
                    cd "${{ env.DEPLOYMENT_DIRECTORY }}"
                    echo "Cleaning up port ${{env.PORT}}..."
                    fuser -k ${{ env.PORT }}/tcp || true

                    if [ -d "${{ env.REPO }}" ]; then
                      cd "${{ env.REPO }}"
                      echo "Fetching Changes..."
                      git stash
                      git fetch origin "${{env.BRANCH}}"
                      git checkout "${{env.BRANCH}}"
                      git pull origin "${{env.BRANCH}}" --rebase
                    else
                      echo "Fetching Source - ${{ env.REPO }}"
                      git clone --branch "${{env.BRANCH}}" https://github.com/rocketstriker999/${{ env.REPO }}
                      cd "${{ env.REPO }}"
                    fi

                    echo "Installing dependencies..."
                    npm install
                    echo "Removing Previous Build..."
                    rm -rf build
                    npm run build
                    echo "Starting app..."
                    npm run start -- -p ${{ env.PORT }} > /dev/null 2>&1 &
                    echo "Starting ${{ env.REPO }}"
                    echo "✅ Deployed & Disconnecting SSH"
                    exit 0
                  EOF
